# Generated by Django 5.2.8 on 2025-11-21 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='maintenance',
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-incident_date']},
        ),
        migrations.AlterModelOptions(
            name='secondsignature',
            options={'ordering': ['signed_at']},
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['signed_at']},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='reportado_por',
            new_name='reported_by',
        ),
        migrations.RenameField(
            model_name='secondsignature',
            old_name='uploaded_at',
            new_name='signed_at',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='uploaded_at',
            new_name='signed_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='secondsignature',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='secondsignature',
            name='firmante',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='firmante',
        ),
        migrations.AddField(
            model_name='incident',
            name='equipment',
            field=models.ForeignKey(blank=True, db_column='equipment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='api.equipment'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='api.maintenance'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='activities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='calificacion_servicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment_type',
            field=models.CharField(default='computer', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='incident_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='observaciones_generales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='observaciones_seguridad',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='observaciones_usuario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='oficina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='placa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='sede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='api.maintenance'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Reporte sin título', max_length=255),
        ),
        migrations.AddField(
            model_name='secondsignature',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_signatures', to='api.maintenance'),
        ),
        migrations.AddField(
            model_name='secondsignature',
            name='signer_name',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='secondsignature',
            name='signer_role',
            field=models.CharField(default='Usuario', max_length=100),
        ),
        migrations.AddField(
            model_name='secondsignature',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/second/thumbnails/'),
        ),
        migrations.AddField(
            model_name='signature',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.maintenance'),
        ),
        migrations.AddField(
            model_name='signature',
            name='signer_name',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='signature',
            name='signer_role',
            field=models.CharField(default='Técnico', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='secondsignature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/second/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.DeleteModel(
            name='MaintenanceReport',
        ),
        migrations.DeleteModel(
            name='MaintenanceTask',
        ),
    ]
