# Generated by Django 5.2.8 on 2025-11-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_maintenancetask_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
