# Generated by Django 5.2.7 on 2025-10-20 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance_signatures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='api.maintenance')),
            ],
        ),
    ]
