# Generated by Django 5.2.8 on 2025-11-23 18:21

from django.db import migrations, models


def add_dependencia(apps, schema_editor):
    # Ensure final legacy column `dependencia_legacy` exists without causing duplicate-column errors.
    # Logic:
    # - If `dependencia_legacy` exists: drop `dependencia` if present (cleanup) and exit.
    # - Else if `dependencia` exists and `dependencia_legacy` does not: rename `dependencia` -> `dependencia_legacy`.
    # - Else (neither exists): create `dependencia_legacy` directly.
    with schema_editor.connection.cursor() as cursor:
        # Check existence of both columns
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'equipment' AND column_name = 'dependencia_legacy';"
        )
        has_legacy = cursor.fetchone()[0] > 0
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'equipment' AND column_name = 'dependencia';"
        )
        has_old = cursor.fetchone()[0] > 0

        if has_legacy:
            # If legacy exists, remove any stray old column to avoid future conflicts
            if has_old:
                cursor.execute("ALTER TABLE `equipment` DROP COLUMN `dependencia`;")
            return

        if has_old and not has_legacy:
            # Rename existing columna dependencia -> dependencia_legacy
            cursor.execute("ALTER TABLE `equipment` CHANGE COLUMN `dependencia` `dependencia_legacy` varchar(255) NULL;")
            return

        # Neither column exists: create the final legacy column
        cursor.execute("ALTER TABLE `equipment` ADD COLUMN `dependencia_legacy` varchar(255) NULL;")


def remove_dependencia(apps, schema_editor):
    # Reverse of add_dependencia: remove any migration-era columns if present
    with schema_editor.connection.cursor() as cursor:
        # Drop dependencia_legacy if exists
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'equipment' AND column_name = 'dependencia_legacy';"
        )
        has_legacy = cursor.fetchone()[0] > 0
        if has_legacy:
            cursor.execute("ALTER TABLE `equipment` DROP COLUMN `dependencia_legacy`;")
            return

        # If for some reason the old column remained, drop it
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'equipment' AND column_name = 'dependencia';"
        )
        has_old = cursor.fetchone()[0] > 0
        if has_old:
            cursor.execute("ALTER TABLE `equipment` DROP COLUMN `dependencia`;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_repair_hierarchy'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE TABLE IF NOT EXISTS `site_configuration` ("
                "`id` bigint AUTO_INCREMENT PRIMARY KEY,"
                "`config` JSON NULL,"
                "`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
                ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
            ),
            reverse_sql="DROP TABLE IF EXISTS `site_configuration`;",
        ),
        migrations.RunSQL(
            sql=(
                "CREATE TABLE IF NOT EXISTS `template` ("
                "`id` bigint AUTO_INCREMENT PRIMARY KEY,"
                "`name` varchar(200) NOT NULL,"
                "`type` varchar(10) NOT NULL,"
                "`description` text NULL,"
                "`html_content` longtext NULL,"
                "`css_content` longtext NULL,"
                "`template_file` varchar(255) NULL,"
                "`fields_schema` JSON NULL,"
                "`created_at` datetime NULL,"
                "`updated_at` datetime NULL"
                ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
            ),
            reverse_sql="DROP TABLE IF EXISTS `template`;",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_dependencia, remove_dependencia),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='equipment',
                    name='dependencia',
                    field=models.CharField(blank=True, db_column='dependencia_legacy', max_length=255, null=True),
                ),
            ],
        ),
    ]

