# Generated by Django 5.2.7 on 2025-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='signature',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_signatures/thumbnails/'),
        ),
    ]
