# Generated by Django 5.2.7 on 2025-10-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_photo_thumbnail_signature_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.equipment'),
        ),
        migrations.AddField(
            model_name='signature',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='api.equipment'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.maintenance'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='maintenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='api.maintenance'),
        ),
    ]
