# Generated by Django 5.2.8 on 2025-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_siteconfiguration_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_configuration',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True, help_text='HTML template with Django template variables')),
                ('css_content', models.TextField(blank=True, help_text='Optional CSS for the template')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('fields_schema', models.JSONField(default=dict, help_text='JSON schema describing template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template',
                'ordering': ['-created_at'],
            },
        ),
    ]
