# Generated by Django 5.2.8 on 2025-11-25 14:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_siteconfiguration_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.Template._templates_upload_to),
        ),
    ]
