# Generated by Django 5.2.7 on 2025-10-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_photo_equipment_signature_equipment_and_more'),
    ]

    operations = [
        # Remove equipment fields from Photo and Signature
        migrations.RemoveField(
            model_name='photo',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='equipment',
        ),
        # Make maintenance fields non-nullable
        migrations.AlterField(
            model_name='photo',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.maintenance'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='maintenance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='api.maintenance'),
        ),
        # Change Report.maintenance on_delete to SET_NULL
        migrations.AlterField(
            model_name='report',
            name='maintenance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='api.maintenance'),
        ),
        # Add missing fields to Report model
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='auth.user'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
