# Generated by Django 5.2.7 on 2025-10-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fix_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage='core.settings.MaintenancePhotoStorage', upload_to='maintenance_photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage='core.settings.MaintenanceThumbnailStorage', upload_to='maintenance_photos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(storage='core.settings.MaintenanceReportStorage', upload_to='maintenance_reports/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(storage='core.settings.MaintenanceSignatureStorage', upload_to='maintenance_signatures/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage='core.settings.MaintenanceThumbnailStorage', upload_to='maintenance_signatures/thumbnails/'),
        ),
    ]
