# Generated by Django 5.2.8 on 2025-11-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_template_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
