# Generated by Django 5.2.7 on 2025-10-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_photo_image_alter_photo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to='maintenance_reports/'),
        ),
    ]
