# Generated by Django 5.2.7 on 2025-10-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_report_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='maintenance_photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(upload_to='maintenance_signatures/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_signatures/thumbnails/'),
        ),
    ]
