# Generated by Django 5.2.7 on 2025-10-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_photo_image_alter_photo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='activities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='calificacion_servicio',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='dependencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('computer', 'Rutina Mantenimiento Preventivo de Equipos de Cómputo'), ('printer_scanner', 'Rutina de Mantenimiento Preventivo para Impresoras y Escáner')], default='computer', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='observaciones_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='observaciones_seguridad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='observaciones_usuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='oficina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='placa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
