# Generated by Django 5.2.7 on 2025-10-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_maintenance_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(storage='core.storage.MaintenanceReportStorage', upload_to='maintenance_reports/'),
        ),
    ]
