# Generated by Django 5.2.7 on 2025-10-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_report_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_incident',
            field=models.BooleanField(default=False, help_text='Marcar si es una incidencia (ej. operador no permite mantenimiento)'),
        ),
    ]
