# Generated by Django 5.2.7 on 2025-10-27 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_maintenance_is_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance_second_signatures/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='maintenance_second_signatures/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_signature', to='api.maintenance')),
            ],
        ),
    ]
