# Generated by Django 5.2.7 on 2025-10-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_secondsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='activities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
