# Generated by Django 5.2.7 on 2025-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_maintenance_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='incident_notes',
            field=models.TextField(blank=True, help_text='Notas específicas del incidente', null=True),
        ),
    ]
