# Generated by Django 5.2.7 on 2025-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_maintenance_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='equipment',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='generated_at',
            new_name='fecha_generacion',
        ),
        migrations.RenameField(
            model_name='secondsignature',
            old_name='uploaded_at',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='uploaded_at',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='model',
            new_name='model_name',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Modelo'),
        ),
    ]
